### ISSUE TITLE
Enable buttons for everyone in the server

### ISSUE THREAD

**Issue by EndritElshani** [devRael1/discordjs-pagination#11]
Hello,
I was wondering if there's a way to make it possible for everyone to go through pages and not only the ones who called the command.

**Comment by devRael1** [comment]
Hi,

You can create a custom filter to always make the filter true with a simple condition like:

`return true;`
`return 1 === 1;`
`return interaction.guild.id === <guildID>`

You just have to make sure that your custom filter always returns the same value, `true`.

**Disclaimer**: doing this implies that several people will be able to use the buttons of the pagination system, so it can create spam buttons.

**Comment by EndritElshani** [comment]
Thank you very much!
