### ISSUE TITLE
Collector Error on v1.8.4

### ISSUE THREAD

**Issue by adriholman** [devRael1/discordjs-pagination#2]
I was testing this package to replace the current one in my bot, but I was having problems with the "end" event of the collector, checking the code a bit and reading around, I think the code for the interaction is wrong.

how is it now:
![image](https://user-images.githubusercontent.com/28815071/188183919-a040dfb7-da2d-44db-8d0a-859c5684f750.png)

How it should be:
![image](https://user-images.githubusercontent.com/28815071/188183728-bc47cbdd-839a-4e38-9345-768e43eed32f.png)

I see that the v2.6.0 has the correct code, but I'm using discord js v13.

**Comment by devRael1** [comment]
Hello,

Yes I fixed the bug on the version for discord.js v14 but not for version 13. I forgot to do it.

I will patch this today

**Comment by devRael1** [comment]
Done with 1.8.6 version ;) 

You can install it now

**Comment by adriholman** [comment]
Thank u so much!!!
