### ISSUE TITLE
Custom Buttons

### ISSUE THREAD

**Issue by PhantomKnight287** [devRael1/discordjs-pagination#3]
Support to add custom buttons with custom handler associated with it.
For example: a custom button labeled `Buy` in embeds of `Store` command so that user can buy the item

**Comment by devRael1** [comment]
I'm not sure I don't understand.
You want a custom handler for each buttons in the pagination system ?

**Comment by PhantomKnight287** [comment]
not each button but some custom buttons

**Comment by devRael1** [comment]
So, you want to put your own buttons with your custom handler for these buttons ?

**Comment by PhantomKnight287** [comment]
yes

**Comment by devRael1** [comment]
No its not possible, you need to personally code this.
