### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by ghost** [devRael1/discordjs-pagination#4]
Can there please be a button for deleting the message or disabling the buttons manually? It would be a lifesaver.

**Comment by devRael1** [comment]
There is no button that can do this. However, I can update the apckage to add this option. 

Describe to me exactly what the button should do.

**Comment by ghost** [comment]
Either delete the message with the buttons when clicked, or atleast disable the buttons when clicked

**Comment by devRael1** [comment]
Both options are possible.
So you have to give the choice of either deleting the complet message or just disabling the buttons in the paging system ?

**Comment by ghost** [comment]
I guess yes.

**Comment by devRael1** [comment]
Okay, I'll see what I can do to update the package

**Comment by ghost** [comment]
Ok, thank you.

**Comment by ghost** [comment]
Um theres no delete button in the new update
I have checked the code and found nothing...

**Comment by devRael1** [comment]
Yes, I said I would do it but not all at once. I just did a small package updates. 
The button system will be a big one so I'll do that in due course.
