### ISSUE TITLE
Pagination page travel

### ISSUE THREAD

**Issue by Grayy12** [devRael1/discordjs-pagination#6]
If you type any number in the range of pages, the number button has a bug that always sets it to 1. I wanted to let you know, but I've already created a simple fix. 

On line 137 - 147 in the pagination.js

```js
if (int > embeds.length) {
    currentPage = embeds.length;
}
else {
    if (int <= 0) {
        currentPage = 1;
    }
    else {
        currentPage = int;
    }
 }
``` 
I changed it to this.

**Comment by devRael1** [comment]
Oh my god the huge code error ahah I am ashamed. 
Thank you for telling me. I patch this in the futur update of the package.

**Comment by Grayy12** [comment]
Np :)
