### ISSUE TITLE
i guess u have to update your types

### ISSUE THREAD

**Issue by anirkm** [devRael1/discordjs-pagination#8]
![image](https://user-images.githubusercontent.com/72000809/224576622-a92c1aa8-3ed3-433c-af96-00baecddde37.png)
![image](https://user-images.githubusercontent.com/72000809/224576650-af8e2771-cdc3-4d3b-8d1c-5e5908c58fde.png)

**Comment by devRael1** [comment]
Send me the code that you have used to create this error pls

**Comment by anirkm** [comment]
![image](https://user-images.githubusercontent.com/72000809/225788338-91aad4b3-dadc-4413-aef8-27d54d191cd4.png)

![Code_nXll6IMI2F](https://user-images.githubusercontent.com/72000809/225788167-982a9529-df87-41f1-b6f4-e789c460b8b2.gif)

**Comment by devRael1** [comment]
Which version of discord.js & pagination package do you use ?
