### ISSUE TITLE
Doesn't work for discord.js v14.9.0

### ISSUE THREAD

**Issue by g0dzcsgo** [devRael1/discordjs-pagination#9]
Can't use this, it crashes when executing pagination function with the message:

node_modules\@devraelfreeze\discordjs-pagination\src\pagination\pagination.ts:118
      initialMessage = await channel.send({
                                     ^
TypeError: Cannot read properties of null (reading 'send')

**Comment by devRael1** [comment]
Send me the code you use to get this error please
